### ISSUE TITLE
Rename `nah` to an english word 

### ISSUE THREAD

**Issue by voddan** [importre/kotlin-unwrap#2]
In the syntax `unwrap(x) {x -> } nah {}` the `nah` function naming is not ideal. 

I suppose _NAH_ is an acronym for "null a.. h.."? Hm, I have no idea. Anyway, it would read better if it were a natural english word, like `unwrap.. or ..`. Additionally, `NAH` very strongly resembles a Russian expletive for "go f**\* yourself" :(

**Comment by importre** [comment]
Hi @voddan. Sorry for the late. I've replaced it with `otherwise`. Is it good?

**Comment by voddan** [comment]
I have no objections :)
