### ISSUE TITLE
Refactor code to make Func class more readable

### ISSUE THREAD

**Issue by skatset** [importre/kotlin-unwrap#3]
I think in Func.kt file you can check variables in more elegant way:

```
    val hasNull = arrayOf<Any?>(t1, t2).contains(null)
    if (!hasNull) block(t1, t2)
    return Unwrap(valid = !hasNull)
```

Instead of

```
    return Unwrap().apply {
        if (t1 != null
                && t2 != null) {
            valid = true
            block(t1, t2)
        }
    }
```

To do it you should make `valid` field as constructor parameter. It make your code more readable and maintanable and also allow explicitly specify `valid` field that is more preferable.

**Comment by importre** [comment]
Hi @skatset . Sorry for the late.
I've regenerated code and will deploy it soon. Thank you 👍
